### ISSUE TITLE
EBS embedded software

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#103]
Relevant section:
DV 1.5.3

**Comment by b1n-ch1kn** [comment]
"someone just needs to write the VCU code to do the triggers or whatever to test it / at least just hold it on - Al I think you and I are fully around that interface? We should probs bring someone else up to speed" - John

**Comment by cwljohnson** [comment]
FSG Rules:
https://www.formulastudent.de/fileadmin/user_upload/all/2022/rules/FS-Rules_2022_v1.0.pdf

FSAE-A Amendum
https://www.saea.com.au/content.cfm?page_id=1616435&current_category_code=21462

EBS Reference Design:
https://www.formulastudent.de/fileadmin/user_upload/all/2019/important_docs/FSG19_EBS_Reference_Design.pdf
