### ISSUE TITLE
Autonomous State Machine

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#105]
Flow chart:
2022 version
![image](https://user-images.githubusercontent.com/77331735/157223407-46be962b-8bea-409d-a8c7-276ea12c4e0b.png)

**Comment by b1n-ch1kn** [comment]
![image](https://user-images.githubusercontent.com/77331735/178918742-b86f3a8f-4eee-4871-90bd-497007660b9b.png)

**Comment by TomFraser** [comment]
Hey @alistair-english @b1n-ch1kn, I would have thought the EBS Checks need to occur before the RES 'start' button is pressed so the EBS is validated before any movement is requested, as the purpose of the button is to command driving. It would be a bit weird to press the go button then the car does some checks then it goes right away.

**Comment by alistair-english** [comment]
Yeah fair - how would you trigger the EBS checks? Like another button press before we send the go signal?

**Comment by alistair-english** [comment]
Discussed with Bradford:

EBS Checks to be run when ASMS is switched on.

VCU is responsible for running the EBS Checks and waiting on the RES "start" button press. When EBS checks and RES start are both "ready to drive" - CAN message gets sent to autonomous systems.
