### ISSUE TITLE
LiDAR mount + cone deflector

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#110]
![image](https://user-images.githubusercontent.com/77331735/159459477-6bad1af4-c10c-4692-adcd-395d527e6ea1.png)
![image](https://user-images.githubusercontent.com/77331735/159459578-40325a3e-1b0c-4999-9019-735dda7dc8b9.png)
![image](https://user-images.githubusercontent.com/77331735/159460238-a54bacb2-97d3-48ca-aeb7-03e339c36de9.png)
![image](https://user-images.githubusercontent.com/77331735/159459843-ebb8239c-0647-464d-8a6b-358d3d07c542.png)

**Comment by cwhit-09** [comment]
![image](https://user-images.githubusercontent.com/98002209/166134148-0753f16f-b282-430e-90ee-e339c475e38b.png)

**Comment by cwhit-09** [comment]
First rev done!

**Comment by cwhit-09** [comment]
- Drawing needs to be checked.
- Bars need to be ordered.

**Comment by b1n-ch1kn** [comment]
5005 Ally sheet
Order in square stock in plain ally, 20mm
Talk to Austin for sheets
Final review

**Comment by b1n-ch1kn** [comment]
Requested quote from:
https://www.shapealuminium.net.au/aluminium-extrusion-suppliers-australia/shape-aluminium-square-box-tube-hollow/19x1.6-radius-aluminium-square-tube
