### ISSUE TITLE
Figure out a good way to mount in /dev/sbg so that it doesnt create an empty folder when the device isnt present

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#12]

**Comment by b1n-ch1kn** [comment]
does this need to be looked at again? or will robostack fix?

**Comment by alistair-english** [comment]
Nah, RoboStack won't fix, this is a docker compose thing, probably won't bother looking at it until we want to use the SBG again

**Comment by alistair-english** [comment]
This is relevant again now as we are planning on using the SBG usb interface + ROS node when running driverless. Good issue for if we want someone to learn more about the docker infrastructure.

**Comment by b1n-ch1kn** [comment]
We want to do IMU+lidar data collection in the carpark early this week while liam is in. Any new ideas for this?

**Comment by alistair-english** [comment]
> We want to do IMU+lidar data collection in the carpark early this week while liam is in. Any new ideas for this?

We can sort this out tomorrow (Monday) - I think there's a straightforward way to do this, just need to do some googling.
