### ISSUE TITLE
Manually check rules differences 20v22 + Addendums

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#120]
2020 vs 2022 FSAE rules
https://fsaeonline.com/cdsweb/gen/DownloadDocument.aspx?DocumentID=1b6bda52-48d0-4286-931d-c9418165fd3e
https://fsaeonline.com/cdsweb/gen/DownloadDocument.aspx?DocumentID=42f9ab71-0a41-4a92-a5d4-aa3d284e5c05

## F.3.5.2.a New - Alternative Tubing Materials
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/175519914-5e0f400a-bd04-4b90-9dd7-73d60f21767f.png)
'22
![image](https://user-images.githubusercontent.com/77331735/175519979-773c8e2f-e596-41c6-9995-862b747dd025.png)

## F.3.5.3.b-c New - Aluminium Tubing
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/178376425-b1af2002-7997-4fc9-bb89-3449a5802524.png)
'22
![image](https://user-images.githubusercontent.com/77331735/178376508-838ffd5d-8c9e-41b2-9cdb-a3bd123494e0.png)

## F.4.1.4 New - Composite Requirements
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/176996247-e99f32ab-7a52-4412-94a6-d8af3d7684e7.png)

## F.4.3.1 New - Laminate Testing
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/178376760-8af82786-f727-49dd-829d-ad85b49afd8b.png)

## F.5.5 New - Chassis Bonding in Regulated Structure
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/156553623-4681ff2d-5f05-4a00-be5c-046cc5586f79.png)

## F.5.10 New - Head Restraint Protection
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/156562763-797cada2-e815-4177-ad69-283f3ebba638.png)

## F.5.11.3 New - External Items
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/156678486-1de40837-4968-4b6d-b488-4367af55899b.png)

## F.7.5.2 New - Front Hoop Attachment
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/177163053-5fb80c65-bf11-4886-9c79-17ef702fd57b.png)

## F.7.6.4 Changed - Side Impact Structure
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177164296-42c70172-dd9c-4f4c-a7a1-e1e12d08cf7c.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177164203-4dcfc502-6a26-4071-bc5b-0f632d7668f5.png)

## F.7.7.2 New - Main Hoop Attachment
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/177165177-b62ae821-1ee4-492c-aa5a-a561df8248ab.png)

## F.7.10.1 Changed - Driver Harness Required Loads **CHECK DATA**
- [ ] '20
![image](https://user-images.githubusercontent.com/77331735/177165577-5e7776e0-6811-43f5-868f-f7bab4ecc617.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177165546-86bd61e8-4eb0-4ed2-89a1-f8a6b52377aa.png)

## F.7.10.2 Changed - Driver Harness Testing
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177165877-eb260bdf-0d4c-43b7-953e-2245f72f63c2.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177165840-0a2472be-6ce9-444a-8b82-ed21aa2debfd.png)

## F.8.3.2 Changed - Composite AIP
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177166278-81b9e102-4bee-435d-a7b1-c8176b7b7164.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177166218-b7a170e3-44d4-45d7-b548-e66950d10b94.png)

## F.8.5 Changed alot - Notable F.8.5.5, new F.8.5.6 - Impact Attenuator Attachment
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177167252-249a79cd-a993-4c0b-a408-980d61242bce.png)
![image](https://user-images.githubusercontent.com/77331735/177167267-5a387008-92f8-4676-9125-14321e914469.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177167223-524ce0ca-9b9b-4e4c-9ae9-3ef196b78793.png)

## F.8.6 Changed alot - Non-crushable Objects
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177167555-1dc4dcdd-9d80-4905-ad6b-c8c929debc58.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177934148-601ef680-4152-4a8a-95ba-a11c4406a0d1.png)
![image](https://user-images.githubusercontent.com/77331735/177167585-e0defc7b-a477-425e-b727-ede11f205a41.png)
![image](https://user-images.githubusercontent.com/77331735/177167620-cf31e7e2-bdaf-45fc-8651-408296fb69aa.png)

### Check items around the accumulator
- [ ] '22
![image](https://user-images.githubusercontent.com/77331735/179468235-140c6509-0e27-47f9-9a4c-ca1dddd24503.png)

## F.8.7.5 New - IA Data
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/177167832-172e7c7e-ea2c-49f1-8302-0c4ebdc5a3a6.png)

## F.10 Significant changes - Accumulator Container - **NOT COMPLIANT**
- [ ] '22
![image](https://user-images.githubusercontent.com/77331735/179468636-26a17b04-f7c8-4dda-8455-69428d507508.png)

## F.11.2 Significant changes - Tractive system protection
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177168837-859dc197-4fb2-4a7c-b11e-d5c4a70e5301.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177168889-2b9a9a52-4187-4fa9-9a91-28df532aabf7.png)
![image](https://user-images.githubusercontent.com/77331735/177168907-aff2dcf7-c5a5-4031-8bf2-8d44dd6bc43a.png)

## T.1.4 Changed - Controls availability
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/177169753-ff579f12-1a36-4cf8-917b-e8fabbe86dfd.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177169788-0188a3df-7fea-4712-895b-87630fc02f08.png)

## T.1.6.3 Changed - Thermal Protection
- [x] '20
![image](https://user-images.githubusercontent.com/77331735/174808613-645c8d19-6646-4ed7-b5fd-ec9f6788873e.png)
'22
![image](https://user-images.githubusercontent.com/77331735/174808746-85a05f9b-564d-4992-a8b0-7cd0c28772df.png)

## T.1.9.4 New - TS Firewalls
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/177170788-1724e004-164b-4a29-a159-c635719ba737.png)

## T.2.5.2 Changed - Lap belt mounting - **CHECK SEAT**
- [ ] '20
![image](https://user-images.githubusercontent.com/77331735/177239724-d213c5ee-1a95-4a99-887f-7126a5be2ce1.png)
'22
![image](https://user-images.githubusercontent.com/77331735/177239864-64508a20-dc65-4ed8-91d5-c94fabec37c5.png)

## T.2.8.3 New - Head restraint
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/177241718-8c1fcae3-4e8d-45d5-9168-f7d58c261adb.png)

## T.3.1.13 New - Brake System Mechanical
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/174813351-a7c6ce27-61d2-4be8-8169-ada22b673bd4.png)

## T.5.3 New - Motor Protection
- [x] '22
![image](https://user-images.githubusercontent.com/77331735/177243892-481b73ab-2b0b-4816-8fce-24254af442e9.png)

## T.6.1.5 New - Pressurized Systems - **NOTE FOR EBS TANK PLACEMENT**
- [ ] '22
![image](https://user-images.githubusercontent.com/77331735/177244140-0984e881-fd59-410f-b7de-e36782633c9b.png)

## T.7 Wording changes (might need checking) - Bodywork and Aerodynamic devices
- [x] '22

## EV.8 All over the place 
Highlighted PDF
### Overcurrent
- [x] '22
- BMU Overcurrent protection - code based
- Missing ADC, can determine if something changes balance significantly from a perfectly balanced pack in a small amount of time @cwljohnson 
- BMU must have watchdog by rules
![image](https://user-images.githubusercontent.com/77331735/177929730-4452dd6f-494c-4f4c-87e1-6566c50039d3.png)

### Grounding on housing
- [ ] '22
- Check grounding on housing
![image](https://user-images.githubusercontent.com/77331735/177931887-dda2227b-0608-4d30-a48c-8aab7e5dafba.png)

### Stickers
- [ ] '22
- All e-stops will need stickers (QEV3 Res + QEV4 everything)
![image](https://user-images.githubusercontent.com/77331735/177931818-e218797c-8cba-4718-b0fb-a6a38c84a4d7.png)

### Accumulator Voltage indicator
- [ ] '22
- Add label?
![image](https://user-images.githubusercontent.com/77331735/180629471-ebe8f115-df33-4ad1-b003-83a4b58db28a.png)

### Interlocks
- [ ] '22
- Need an interlock to each outboard motor
![image](https://user-images.githubusercontent.com/77331735/180629951-fbf1660b-ed5d-4669-8ee1-5f6f77839740.png)

**Comment by cwljohnson** [comment]
RE EV.8.3.4, turns out the CMU chip we're using (L9963E) has built in functionality for detecting blown fuses (open cell detection), so that should cover EV.8.3.4.b, then we should be good for EV.8.3.4 as we already do / will do the rest

**Comment by b1n-ch1kn** [comment]
Have broken out indiv rules we need to check or get exemptions for. closing this
