### ISSUE TITLE
Cooling system

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#151]
Individual reserviors for the two radiators.
Out of line-of-site to 'driver'.
Above highest point in radiators.

TODO:
- [x] Design reservoir 
- [x] Design mounting solution (potentially adjusting pump)
- [x] Establish suitable parts (stores / our stock)
- [x] Order parts
- [ ] Manufacture+Install

**Comment by b1n-ch1kn** [comment]
Second set of reservoirs were never made - cap for reservoir needs purchasing. 
Then welding together and mounting somewhere (suggestion was above the pumps)

**Comment by GeorgyUshakov** [comment]
From cooling reservoirs thread: need 2x-06 and 2x-08 Al male weld-on fittings, had 2x-06 as of 20th Jan, need to buy 2x-08 from https://www.speedflowdirect.com.au/aluminium-male-weld-on

**Comment by GeorgyUshakov** [comment]
Need 2x of these caps: https://www.dicksmith.com.au/da/buy/speedparts-aeroflow-billet-radiator-cap-32mm-11b-complete-with-billet-cover-af64-5032blk/

+ 2x of these necks: https://aeroflowperformance.com/af64-0032-billet-radiator-neck-weld-on

**Comment by b1n-ch1kn** [comment]
All components, minus waterjet parts, have been sorted and ready for welding
