### ISSUE TITLE
LiDAR based cone detection

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#16]
Use Velodyne VLP32 to process ground points and eliminate them, then cluster remaining points to match approximate cone dimensions.

Point cloud on node /velodyne_points
or if on Formula Student Driverless Simulator, point cloud on node /fsds/lidar/Lidar1

**Comment by liamferrante** [comment]
LiDAR computer vision pipeline for the perception of accurate cone location has been developed. Further tuning should be able to achieve increased algorithm speed and accuracy.
