### ISSUE TITLE
Jetson container for ZED2i

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#19]
Create a docker container for the Jetson Xavier with ZED SDK and ZED ROS2 wrapper. Will allow image, depth, and IMU data output from the ZED stereo camera to be published as ROS nodes

**Comment by alistair-english** [comment]
Kinda done - worked for demo.
Will be addressed more by https://github.com/QUT-Motorsport/QUTMS_Driverless/issues/25
