### ISSUE TITLE
Upgrade to Galactic then update ROS installation in docker to RoboStack

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#25]
https://github.com/RoboStack
https://robostack.github.io/galactic.html

Should mean we can unify our installation of ROS again cause RoboStack supports ARM

Requires a galactic update first.

**Comment by b1n-ch1kn** [comment]
Some galactic packages for ARM aren't in Robostack yet in like vision (for cv_bridge), and velodyne drivers aren't even available for linux :(

![image](https://user-images.githubusercontent.com/77331735/145346293-aa6840db-51bc-4092-b867-df92c3cb8857.png)

![image](https://user-images.githubusercontent.com/77331735/145346442-f0dc1e20-7c55-423b-8050-950533d33445.png)

**Comment by b1n-ch1kn** [comment]
given this, should we not use dockerhub for images?

**Comment by alistair-english** [comment]
> Some galactic packages for ARM aren't in Robostack yet in like vision (for cv_bridge), and velodyne drivers aren't even available for linux :(
> 
> ![image](https://user-images.githubusercontent.com/77331735/145346293-aa6840db-51bc-4092-b867-df92c3cb8857.png)
> 
> ![image](https://user-images.githubusercontent.com/77331735/145346442-f0dc1e20-7c55-423b-8050-950533d33445.png)

https://robostack.github.io/galactic.html has CV deps on ARM (which should be all we need - hence why we need to upgrade to galactic first). Plus, we can always ask for packages we want to be added - pretty sure they just havent had much ARM usage so havent bothered  adding packages.

**Comment by alistair-english** [comment]
> given this, should we not use dockerhub for images?

wdm by this?

**Comment by b1n-ch1kn** [comment]
Ok, sounds good.

Yesterday you mentioned how we'd have a system where the images will be built, uploaded to docker hub, and pulled on the car, so I made a task: https://github.com/QUT-Motorsport/QUTMS_Driverless/issues/34

**Comment by alistair-english** [comment]
https://vimeo.com/649654404

**Comment by b1n-ch1kn** [comment]
I like the yaml file for all the dependancies.
Link for dependancies we require:
https://robostack.github.io/galactic.html

Also, do we have to add to the yaml file everything thats in each package.xml file? or can we install rosdep to source it automatically?

**Comment by b1n-ch1kn** [comment]
Will turn the `conda_instructions.txt` into wiki page too
