### ISSUE TITLE
Fix colcon build issue with build,install,log perms

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#27]
![unknown](https://user-images.githubusercontent.com/77331735/144422030-07991043-83ff-450f-b25a-425ff77a9be0.png)

In perception (and possibly other containers) colcon build throws a permission error writing to a log file.

Temporary fix:
`sudo rm -rf build install log`

Might be a `chown` fix

**Comment by b1n-ch1kn** [comment]
What fixed this btw?

**Comment by alistair-english** [comment]
> What fixed this btw?

https://github.com/QUT-Motorsport/QUTMS_Driverless/blob/master/docker/Dockerfile#L82
