### ISSUE TITLE
Scripts to run packages on container startup 

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#35]
Saves having to colcon build, source setup, and run packages for demonstration + data collection if we can get steering, zed camera, jetson processing to auto start, then we can just start nav and a recording container if needed.

Idk if this would entail launch files or smth that can autorun multiple containers - just a thought

**Comment by alistair-english** [comment]
Park this until https://github.com/QUT-Motorsport/QUTMS_Driverless/issues/25 has a resolution

**Comment by b1n-ch1kn** [comment]
Yeah, was planning to. With there was a "blocks issue" label

**Comment by alistair-english** [comment]
This was done during the robostack refactor
