### ISSUE TITLE
Building Images ip instructions should be more specific

### ISSUE THREAD

**Issue by TheEppicJR** [QUT-Motorsport/QUTMS_Driverless#37]
> and copy the value next to 'IPV4 Address'.

should be 

> and copy the value next to 'IPV4 Address' under 'Ethernet adapter vEthernet (WSL)'.

**Comment by b1n-ch1kn** [comment]
Should be this address:

![image](https://user-images.githubusercontent.com/77331735/145804405-a1fc1579-2baf-4c93-a59c-969297676d44.png)

Though, I haven't tested whether the "Ethernet adapter vEthernet (WSL)" IPv4 address works too

**Comment by alistair-english** [comment]
I believe both will work

**Comment by b1n-ch1kn** [comment]
In which case, did we want to change the .env lines that require user input from `{IPV4 HERE} ` to `export WSL_HOST=$(ip route | awk '{print $3; exit}')` ? i believe this automatically gets the vEthernet WSL

**Comment by TheEppicJR** [comment]
I am on wifi and have "Wireless LAN adapter Wi-Fi" which does not work for me, but that may just also be that my LAN is a bit sus, either way I believe that pointing it to the vEthernet WSL is a better default.

**Comment by alistair-english** [comment]
> In which case, did we want to change the .env lines that require user input from `{IPV4 HERE}` to `export WSL_HOST=$(ip route | awk '{print $3; exit}')` ? i believe this automatically gets the vEthernet WSL. btw this was just copied from my ubuntu bashrc file but we'd change it to `SIM_HOST=` not `export WSL_HOST=`

I attempted to add a subshell (the `$(...)`) into the envfile before but makefiles dont support it.

I see you've updated the wiki already @b1n-ch1kn so will close this issue.

**Comment by b1n-ch1kn** [comment]
ah oh well, for now a fixed IP works
