### ISSUE TITLE
Jetson Xavier failure to reboot

### ISSUE THREAD

**Issue by liamferrante** [QUT-Motorsport/QUTMS_Driverless#38]
On track day, when rebooting the Jetson Xavier, it did not turn back on. 

Unplugging and plugging the power back in did not fix it. 

However, plugging the Jetson into a display using HDMI seemed to turn it on. Perhaps this was a coincidence.

**Comment by b1n-ch1kn** [comment]
I've seen this happen on raspberry pi's - seems to need an output to boot sometimes.

**Comment by alistair-english** [comment]
I'm not convinced about the display thing though cause we've booted it heaps of times headless.

**Comment by b1n-ch1kn** [comment]
havent seen this since recorded here, closing
