### ISSUE TITLE
A way to share python libraries across nodes

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#42]
We have a good amount of "common" code for managing things like Points, Rectangles, Cones that has been copied around the place. Need to find a way to put these in a common space that can be imported by all nodes.

**Comment by b1n-ch1kn** [comment]
Was doing some work in the controllers area, our Point dataclass isnt used in vision pipeline. There, the ROS2 Point message type is used instead. So for now, there are no duplicates / need for common code

**Comment by b1n-ch1kn** [comment]
For now, created a `driverless_common` package where python files used by multiple packages can be added
