### ISSUE TITLE
Get sbg_driver and velodyne packages onto robostack

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#43]
We are moving towards using robostack to manage our ROS environment, at the moment, ROS 2 packages we use `sbg_driver` and `velodyne` are not on robostack.

https://robostack.github.io/Contributing.html

**Comment by b1n-ch1kn** [comment]
So i got the sbg driver to make me a recipe then build
![image](https://user-images.githubusercontent.com/77331735/146633104-515728f3-1990-43de-8977-fbf70a299608.png)

just not sure where the built stuff went lol
![image](https://user-images.githubusercontent.com/77331735/146633125-f861d5a3-0d34-4cbc-bd3a-4b1584bb21ab.png)

**Comment by b1n-ch1kn** [comment]
SBG driver submitted as a pull request to [robostack ](https://github.com/RoboStack/ros-galactic/pull/65) (lets see how it goes)

**Comment by b1n-ch1kn** [comment]
Not having any more luck with velodyne_pointcloud - all other velodyne packages work (msgs, laserscan, driver) but to get our the velodyne driver outputting we need the pointcloud package.

Gets to here:

![image](https://user-images.githubusercontent.com/77331735/146733549-be9d42e1-ac53-4401-b0aa-6eb6fe8c26cd.png)
![image](https://user-images.githubusercontent.com/77331735/146733589-f4217a47-8710-42b8-908c-c5b435616c74.png)
![image](https://user-images.githubusercontent.com/77331735/146735070-d21066dd-634c-45f7-8fb0-5a1b023b6270.png)


[CMakeError.log](https://github.com/QUT-Motorsport/QUTMS_Driverless/files/7743522/CMakeError.log)
[CMakeOutput.log](https://github.com/QUT-Motorsport/QUTMS_Driverless/files/7743524/CMakeOutput.log)

**Comment by Tobias-Fischer** [comment]
Hiya, for you guys I'll be happy to have a look once I'm back from leave on 4 Jan. Please ping me then.

**Comment by Tobias-Fischer** [comment]
That's actually an easy one, add two lines like that for the point cloud package: https://github.com/RoboStack/ros-galactic/blob/06f1f91b1c35896847bc48839103fa6b092d4079/patch/dependencies.yaml#L6-L7

**Comment by b1n-ch1kn** [comment]
> That's actually an easy one, add two lines like that for the point cloud package: https://github.com/RoboStack/ros-galactic/blob/06f1f91b1c35896847bc48839103fa6b092d4079/patch/dependencies.yaml#L6-L7

Yep this worked. Thanks again!

**Comment by b1n-ch1kn** [comment]
Thanks for your help today @Tobias-Fischer 
Looking forward to seeing our system come together on RoboStack soon.
