### ISSUE TITLE
EBS Schematic Review

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#55]
1. Condense the FSG EBS handbook requirements + any other documentation you have on the EBS into a one pager requirements doc on the new wiki
2. You can then ask Mark to review the current schematic against the requirements we've written in the wiki doc

**Comment by b1n-ch1kn** [comment]
Rules compliance https://github.com/QUT-Motorsport/QUTMS_Driverless/issues/74
