### ISSUE TITLE
SBG CAN Messages

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#58]

**Comment by b1n-ch1kn** [comment]
Possibly blocked by https://github.com/QUT-Motorsport/QUTMS_Driverless/issues/12 ?

**Comment by TomFraser** [comment]
> Possibly blocked by #12 ?

Nope, this just refers to adding the Composers & Parsers for the SBGs ECAN protocol, #12 refers to the ECOM protocol which is over Serial.

**Comment by TomFraser** [comment]
Investigating this, which specific information would you guys like from the SBG (position, velocity, acceleration, UTC time etc)? Do we have topics planned for passing the information onto? @alistair-english @b1n-ch1kn

**Comment by alistair-english** [comment]
https://github.com/SBG-Systems/sbg_ros2_driver

Have a look and see what message types this one uses. Haven't got any plans for what exact data we want but if we can keep it flexible that would be good.
