### ISSUE TITLE
ZED Roll hoop mount

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#59]
For Caitlin once shes' signed up. @b1n-ch1kn can add details

**Comment by cwhit-09** [comment]
Submitted a HEAT request today.

**Comment by b1n-ch1kn** [comment]
New proposal (cause 1st one didnt fit).
We hang it upside down, with a cut-out to clear TSAL (havent measured that up fully yet)
![image](https://user-images.githubusercontent.com/77331735/155670804-fabd30a6-7da6-4aa7-a2a1-6b9d59a4e0b6.png)

**Comment by b1n-ch1kn** [comment]
This was sent off to printing on the weekend
