### ISSUE TITLE
Add Orange Cones to YOLO Model

### ISSUE THREAD

**Issue by alistair-english** [QUT-Motorsport/QUTMS_Driverless#61]
Is this a task that needs tracking? Probably looking for @b1n-ch1kn for comment here...

**Comment by b1n-ch1kn** [comment]
Yeah this is good. First, we need some data. carpark or track pushing our trolley around with blue, yellow and orange cones setup. I won't be in for the rest of the week, might see about next week or if anyone is in earlier

**Comment by alistair-english** [comment]
@b1n-ch1kn to collect more data for this at some point

**Comment by alistair-english** [comment]
@Braytho29 to talk to @b1n-ch1kn about making a PR with wieights file
