### ISSUE TITLE
Mapped pursuit control

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#89]
Now we have a 'mapped' path in the sim, we can make a control system to follow the path + adjust velocity accordingly.

`sim_planning` package

Photo from `mapper` script
![image](https://user-images.githubusercontent.com/77331735/152962090-088ac9e8-03e8-4fc1-afd6-51266d53f821.png)

**Comment by Grant-ed** [comment]
Got an initial working commit https://github.com/QUT-Motorsport/QUTMS_Driverless/commit/898aaf6a4bd13f791f18354cf10541443fdac1dd

https://user-images.githubusercontent.com/43590806/154198070-897667c9-8e18-4137-8ea9-ed69ef4b500c.mp4
