### ISSUE TITLE
Simulate sensors in FSDS

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#95]
- [x] Make a middleman node to take the stereo from FSDS and give a depth map - same specs as ZED2i camera
- [x] bring back the old lidar code - single laserscan w/o complex ground removal

Aim to simulate sensor fusion as we dont have odom data yet

**Comment by TheEppicJR** [comment]
I tried to use the robot_localization ROS package (which ends up being like 3 nodes) to act as the EKF when connected to the sim, but I haven't gotten it to work yet (a conda thing I assume) but the messages types it wants are directly compatible with what comes out of the sim as it stands.
This was the setup I was trying to follow: http://docs.ros.org/en/noetic/api/robot_localization/html/integrating_gps.html
I'm pretty sure you have to install it with rosdeps but idk it doesn't have actual install docs anywhere

**Comment by b1n-ch1kn** [comment]
For this i was mostly going to try and reproduce our perception system to then look into fusion without having real odom data. But yeah we'd need some EKF for that.

The guys at RoboStack have made the `robot_localisation` package available on conda if you
`mamba install robot_localisation` (+ include it in the `conda_requirements` file in its package for the future)

![image](https://user-images.githubusercontent.com/77331735/154919032-b4b56b5a-166e-4435-b89f-d40b09723d70.png)
