### ISSUE TITLE
MPC Implementation

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#98]
https://github.com/QUT-Motorsport/Spacial-MPC

**Comment by b1n-ch1kn** [comment]
Check out https://github.com/TheEppicJR/QUTMS_Driverless/tree/master/src/navigation/mpc_planner
Might give some inspiration

**Comment by Harl-Towne** [comment]
- [ ] Convert non-essential constraints to soft constraints
 - [ ] Speed up solving (problem seems to be very stiff and ode45 is struggling)
 - [ ] Connect MPC in MATLAB to fs simulation 
 - [ ] Test + Tune in sim
 - [ ] rewrite MATLAB code (or just port into C++)
 - [ ] port into C++

**Comment by b1n-ch1kn** [comment]
closing, moving to timeline planner
