### ISSUE TITLE
SBG 3D printed mount

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#99]

**Comment by TomFraser** [comment]
Hello, please refer to my fantastic drawing concept. The drawings of the SBG can be found here: https://www.sbg-systems.com/setup/, we are using the Ellipse-N.
![SBG Mount](https://user-images.githubusercontent.com/8476297/155256337-2c2e62b5-e313-4d98-88bc-38cd746c41e4.png)

**Comment by TomFraser** [comment]
![image](https://user-images.githubusercontent.com/8476297/155281919-170168cb-8dcf-4275-8567-be61a437e038.jpeg)

Here please

**Comment by cwhit-09** [comment]
![image](https://user-images.githubusercontent.com/98002209/156907190-467a61f0-ef04-49c6-a567-1ce1d9e4d790.png)

**Comment by cwhit-09** [comment]
It's upside down.

**Comment by b1n-ch1kn** [comment]
This was sent off to printing on the weekend
